#PREDICTING FINE PARTICULATE MATTER IN BEIJING

#Need to run prior:
#merge_beijing.r
#scrape_weather.r OR use datafiles in Github (better!)
#merge_weather.r

#Create the outcome variables:
#Average PM 2.5 levels for the next five days
##Issue: This should work instead of the kludgy list of numbers
##cat(paste(shQuote(0:23, type="cmd"), collapse=", "))
##But for some reason it's producing a null at the end of the list. Why?

load("beijing_air_weather.dta")

names(air) <- gsub("__", "_", names(air), fixed = TRUE)

air$average.today <- rowMeans(air[,c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","23")], na.rm=T)

names(air)[5:28] <- paste(as.character("particulate"), 0:23, sep="_")

#Create future air quality variables

air$average.d1 <- c(air$average.today[2:length(air$average.today)], NA)
air$average.d2 <- c(air$average.today[3:length(air$average.today)], NA, NA)
air$average.d3 <- c(air$average.today[4:length(air$average.today)], NA, NA, NA)
air$average.d4 <- c(air$average.today[5:length(air$average.today)], NA, NA, NA, NA)
air$average.d5 <- c(air$average.today[6:length(air$average.today)], NA, NA, NA, NA, NA)

names(air)
#I will use the actual next day noon conditions as the "forecast"
#Obviously real forecasts are not this accurate!
#Later I will attempt to add historical forecasts.

air$forecast_temp <- c(air$Temp_12_00_PM[2:length(air$Temp_12_00_PM)], NA)
air$forecast_dew <- c(air$Dew_Point_12_00_PM[2:length(air$Dew_Point_12_00_PM)], NA)
air$forecast_humidity <- c(air$Humidity_12_00_PM[2:length(air$Humidity_12_00_PM)], NA)
air$forecast_pressure <- c(air$Pressure_12_00_PM[2:length(air$Pressure_12_00_PM)], NA)
air$forecast_visibility <- c(air$Visibility_12_00_PM[2:length(air$Visibility_12_00_PM)], NA)
air$forecast_wind_dir <- c(air$Wind_Dir_12_00_PM[2:length(air$Wind_Dir_12_00_PM)], NA)
air$forecast_wind_speed <- c(air$Wind_Speed_12_00_PM[2:length(air$Wind_Speed_12_00_PM)], NA)
air$forecast_conditions <- c(air$Conditions_12_00_PM[2:length(air$Conditions_12_00_PM)], NA)


#As a first cut, we'll use 2008-2013 data to train the models and validate on 2014
#Create the training set
train <- air[which(air$Year_x<2014),]
variables <- c("average.d1", "particulate_23","Temp_11_00_PM","Dew_Point_11_00_PM","Humidity_11_00_PM","Pressure_11_00_PM","Visibility_11_00_PM","Wind_Dir_11_00_PM","Wind_Speed_11_00_PM","Conditions_11_00_PM", "forecast_temp", "forecast_dew", "forecast_humidity", "forecast_pressure", "forecast_visibility", "forecast_wind_dir", "forecast_wind_speed", "forecast_conditions")
train <- train[,variables]

#Create the validation set, while dealing with some factors that are unique to 2014
validation <- air[which(air$Year_x==2014),]
validation$Wind_Dir_11_00_PM[which(validation$Wind_Dir_11_00_PM=="Calm")] <- NA
validation$Conditions_11_00_PM[which(validation$Conditions_11_00_PM=="Thunderstorm")] <- NA
validation$Conditions_11_00_PM[which(validation$Conditions_11_00_PM=="Partial Fog")] <- NA
validation <- validation[,variables]

####################################
#####PREDICTING SMOG IN BEIJING#####
####################################

###SUPERLEARNER ALGORITHM###

library(SuperLearner)
library(randomForest)
library(rpart)
library(glmnet)
library(earth)
library(polymars)

#The SuperLearner algorithm combines prediction algorithms
#and cross-validates on them. In this run I will use 
#random forests, regression trees, generalized linear model,
#and adaptive regression splines.


#Need to create a dataset with NAs removed
#Later we can attempt to impute missing data
train.SL <- na.omit(train)
validation.SL <- na.omit(validation)

#Create the library of algorithms to use
SL.library <- c("SL.randomForest", "SL.mean", "SL.rpart", "SL.glmnet", "SL.earth", "SL.polymars")

#Run the SuperLearner algorithm
fit.SL <- SuperLearner(Y = train.SL$average.d1, X = train.SL[,variables[2:18]], newX = validation.SL[,variables[2:18]], SL.library = SL.library,
                       verbose = TRUE, method = "method.NNLS")

#Calculate the prediction rate
error.SL <- as.vector(fit.SL$SL.predict-validation.SL$average.d1)
length(which(error.SL<25))/length(which(is.na(error.SL)==FALSE))

############################################
## RESULT: 76 percent predicted correctly ##
############################################

#Now I'll compare with the predictions generated by other procedures

###LEAST SQUARES REGRESSION###

model.ols <- lm(average.d1~particulate_23+Temp_11_00_PM+Dew_Point_11_00_PM+Humidity_11_00_PM+Pressure_11_00_PM+Visibility_11_00_PM+Wind_Dir_11_00_PM+Wind_Speed_11_00_PM+Conditions_11_00_PM+forecast_temp+forecast_dew+forecast_humidity+forecast_pressure+forecast_wind_dir+forecast_wind_speed, data=train)

summary(model.ols)

#The range for each category in the official Air Quality Index is 50
#(e.g. Healthy is 0 to 50; moderate 51 to 100)
#Arbitarily, I'll count a prediction as correct if it's +/- 25 of the actual value

error.ols <- as.vector(predict(model.ols, validation, type="response")-validation$average.d1)
length(which(error.ols<25))/length(which(is.na(error.ols)==FALSE))

##OLS: 71 percent prediction rate, as arbitrarily defined above##

###POISSON REGRESSION###

model.poisson <- glm(average.d1~particulate_23+Temp_11_00_PM+Dew_Point_11_00_PM+Humidity_11_00_PM+Pressure_11_00_PM+Visibility_11_00_PM+Wind_Dir_11_00_PM+Wind_Speed_11_00_PM+Conditions_11_00_PM+Conditions_11_00_PM+forecast_temp+forecast_dew+forecast_humidity+forecast_pressure+forecast_wind_dir+forecast_wind_speed, data=air[which(air$Year_x<2014),], family="poisson")

summary(model.poisson)

error.poisson <- as.vector(predict(model.poisson, validation, type="response")-validation$average.d1)
length(which(error.poisson<25))/length(which(is.na(error.poisson)==FALSE))


###RANDOM FORESTS###

library(randomForest)

#For NA the randomForest function does not automatically delete listwise
#So I will manually do so... Future versions will use multiple imputation.

train.forest <- na.omit(train)

set.seed(822)

fit.forest <- randomForest(average.d1~particulate_23+Temp_11_00_PM+Dew_Point_11_00_PM+Humidity_11_00_PM+Pressure_11_00_PM+Visibility_11_00_PM+Wind_Dir_11_00_PM+Wind_Speed_11_00_PM+Conditions_11_00_PM+Conditions_11_00_PM+forecast_temp+forecast_dew+forecast_humidity+forecast_pressure+forecast_wind_dir+forecast_wind_speed, data=train.forest, importance=TRUE, ntree=2000)

varImpPlot(fit.forest)
validation
error.forest <- as.vector(predict(fit.forest, validation, type="response")-validation$average.d1)
length(which(error.forest<25))/length(which(is.na(error.forest)==FALSE))

### Puzzling failure; a 27 percent prediction rate
### An issue to invesigate

